[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[project]
name = "pyocmf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ciso8601>=2.3.2",
    "phonenumbers>=9.0.10",
    "pydantic-extra-types>=2.10.1",
    "pydantic>=2.10.4",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]

[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
plugins = ['pydantic.mypy']
mypy_path = "src"

[tool.pytest.ini_options]
addopts = "-v"
testpaths = [
    "test",
]
pythonpath = ["src", "test"]
