[project]
name = "pyocmf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.4"
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pyocmf",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]

[tool.uv.sources]
pyocmf = { workspace = true }

[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
namespace_packages = true
plugins = ['pydantic.mypy']
